"""empty message

Revision ID: 00aba9c5a9ea
Revises: e058c101a4af
Create Date: 2018-11-24 11:58:07.039530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aba9c5a9ea'
down_revision = 'e058c101a4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('faces_extracted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'faces_extracted')
    # ### end Alembic commands ###
