"""empty message

Revision ID: 66af2b96b48d
Revises: 4619593462e2
Create Date: 2018-10-27 20:08:37.270904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66af2b96b48d'
down_revision = '4619593462e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('perm_twtimgdl', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'perm_twtimgdl')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
