"""empty message

Revision ID: 6a105a919baf
Revises: e444efc8fb9d
Create Date: 2018-11-16 18:23:44.237721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a105a919baf'
down_revision = 'e444efc8fb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rq_job', sa.Column('result', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rq_job', 'result')
    # ### end Alembic commands ###
