"""empty message

Revision ID: 7096600b23f6
Revises: d8769e19e242
Create Date: 2018-11-20 00:14:06.623244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7096600b23f6'
down_revision = 'd8769e19e242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('identity', sa.Enum('WJSN_SEOLA', 'WJSN_XUANYI', 'WJSN_BONA', 'WJSN_EXY', 'WJSN_SOOBIN', 'WJSN_LUDA', 'WJSN_DAWON', 'WJSN_EUNSEO', 'WJSN_CHENGXIAO', 'WJSN_MEIQI', 'WJSN_YEOREUM', 'WJSN_DAYOUNG', 'WJSN_YEONJUNG', 'FROMIS_SAEROM', name='identity'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'identity')
    # ### end Alembic commands ###
