"""empty message

Revision ID: 898e52f17492
Revises: 6e2b914a60aa
Create Date: 2018-11-22 14:08:46.229577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898e52f17492'
down_revision = '6e2b914a60aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('embedding', sa.BLOB(), nullable=True),
    sa.Column('filepath', sa.VARCHAR(), nullable=True),
    sa.Column('identity_id', sa.INTEGER(), nullable=True),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
