"""empty message

Revision ID: a4805e8d0a23
Revises: 00aba9c5a9ea
Create Date: 2018-11-24 13:15:55.508645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4805e8d0a23'
down_revision = '00aba9c5a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_filepath_original', sa.String(), nullable=True),
    sa.Column('_filepath_resize', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('faces_extracted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath_original', sa.String(), nullable=True),
    sa.Column('filepath_resize', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
