"""empty message

Revision ID: c1230b7900d7
Revises: 21b4754b767d
Create Date: 2018-11-24 14:26:29.939670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1230b7900d7'
down_revision = '21b4754b767d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('identity_id', sa.Integer(), nullable=True))
    op.add_column('face', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'face', 'image', ['image_id'], ['id'])
    op.create_foreign_key(None, 'face', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face', type_='foreignkey')
    op.drop_constraint(None, 'face', type_='foreignkey')
    op.drop_column('face', 'image_id')
    op.drop_column('face', 'identity_id')
    # ### end Alembic commands ###
