"""empty message

Revision ID: c78eded20aed
Revises: 60273289c3d1
Create Date: 2018-11-16 21:09:23.209531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78eded20aed'
down_revision = '60273289c3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rq_job', sa.Column('process', sa.String(length=72), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rq_job', 'process')
    # ### end Alembic commands ###
