"""empty message

Revision ID: e058c101a4af
Revises: 898e52f17492
Create Date: 2018-11-22 14:11:25.945501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e058c101a4af'
down_revision = '898e52f17492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    # ### end Alembic commands ###
