"""empty message

Revision ID: e444efc8fb9d
Revises: e868e808abc4
Create Date: 2018-11-06 23:38:40.906599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e444efc8fb9d'
down_revision = 'e868e808abc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rq_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('enqueued_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rq_job')
    # ### end Alembic commands ###
